### ISSUE TITLE
Armor bonus skills

### ISSUE THREAD

**Issue by kennedyoliveira** [gatheringhallstudios/MHWorldData#11]
Hello!

I don't see the armor bonus skills currently in the database, like 2 pieces of rathalos set given rathalos mastery (i.e. Elementa Crit) is this information somewhere? Are there any plans for it to be added?

Thank you!

**Comment by CarlosFdez** [comment]
Hey,

Unfortunately we still do not have armor bonus skills in the database. I'm still waiting for the PC release of World so I can't add it myself, and its not really available anywhere else either (though there is some on the fextra wiki).

What I could do for now is add support for Armor Set Bonus skills, even if there's no data to populate it yet.

**Comment by kennedyoliveira** [comment]
Humm I see, well, I'll start adding this information then, I play on PS4 and most of the armors, will start with it.

**Comment by CarlosFdez** [comment]
Sure! That'd help a lot!

I'm currently working on something else in the meantime, but the format I'm thinking is the following:

new: *armorset_bonus_base.csv*
`name_en, name_ja`
^ Don't really need this one, can be made from the others automatically

new: *armorset_bonus_data.csv*
`name_en, skill, threshold`
^ This would be the actual data

update: *armorset_base.csv*
add a `bonus` column that is the english name of the set bonus
^ Most important. Would make using Japanese sources possible.


The bonus base would contain translation data, and the data would contain the actual skills. Since the same armor set can have more than one skill, there can be multiple rows for the same armorset in the data table.

**Comment by CarlosFdez** [comment]
Just pushed the prerequisite work

**Comment by CarlosFdez** [comment]
I now have the means to start gathering that info. @kennedyoliveira have you been able to work on it or should I take over?

**Comment by kennedyoliveira** [comment]
@CarlosFdez please, go ahead, unfortunately I wasn't able to make any progress, I'll be free next week, if you need help like confirmations or anything, please let me know and I'll be glad and faster to help :)

**Comment by kennedyoliveira** [comment]
Also, one note, there are bonus skills which can come for different armors, the most different one is `Rathalos Mastery` it can come from multiple armor sets, don't know if you accounted that already, just fyi

**Comment by CarlosFdez** [comment]
I'll probably get on it soon then. But yeah that was accounted for, as well as the possibility that the same armorset can result in multiple skills.

**Comment by kennedyoliveira** [comment]
Perfect, that's all there is :)

**Comment by CarlosFdez** [comment]
Finished and caught up with the current sets. If you see anything wrong let me know!
