### ISSUE TITLE
Holy Sabers (id: 291 in weapons table) have wrong rarity

### ISSUE THREAD

**Issue by Shevraar** [gatheringhallstudios/MHWorldData#24]
Hi there!
First of all I wanted to thank you for the awesome work you've done extrapolating all the data and formatting it nicely in a database.
I've noticed that the Holy Sabers (as mentioned in the subject) have a wrong rarity (252, instead of 7). The csv file you've used seems to be fine, so I don't know where the issue could be.

**Comment by CarlosFdez** [comment]
Hey, no problem! 

If you're using the newest release, that's because the current release is a bit old and the rarity was only fixed recently. We were informed of a reverse engineering project created by MHWorld modders, and started using it to correct existing data. I didn't feel right putting out a new release until all new information has been merged in, and we're still missing lunastra weapons.

Figuring out a merge process for HBGs have been a current stumbling block, will need to come up with a solution.

**Comment by Shevraar** [comment]
If you need a hand I can try to help.
In the meantime, thank you for your work.

**Comment by CarlosFdez** [comment]
No problem! I don't think I'll need a hand for it (did some thinking and came up with an idea), but if there's anything you need for your own uses that you think would be benefit other people as well feel free to make a pr (or an issue beforehand).

The stumbling block was that currently weapon -> weapon ammo in the CSV is linked by a custom made name, and the weapon_ammo table has deviation and special ammo. Meanwhile the game binaries link weapon -> ammo by a numerical id, and deviation/special ammo are in the weapon object itself. Couldn't figure out how to convert the data but then I found out how Weapon -> Weapon Tree was linked and will use that to derive names, and compare dictionaries for incrementing ammo table names.

**Comment by CarlosFdez** [comment]
Bit of a late update but its been fixed.
