### ISSUE TITLE
Foreign Keys -- are they working?

### ISSUE THREAD

**Issue by ardeaf** [gatheringhallstudios/MHWorldData#34]
I thought that foreign keys, when referencing composite primary keys, need to also reference the full composite (can't be partial)?

For example any foreign keys that reference `location_text` need to have `(id, lang_id)` as the foreign key.

On my phone, so typing from memory, but will be able to provide a code example when I get back on my PC if this doesn't make sense.

Reproduction would be to run a `PRAGMA foreign_key_check;` on the database
 
I'm unfamiliar with sqlite but the error about an foreign key constraint violation popped up when I was migrating the db to a postgresql server

**Comment by CarlosFdez** [comment]
Having trouble understanding the issue. A code example would definitely be welcome as I'm not a DBA. There might be some nonsense we're doing that happens to work in SQLite but causes all hell to break loose in another DBMS.

The general idea though is that translations are done via joining to a *_text table. However in the case of location, there is no master table as there was no non-textural location specific data. For that table, you have to either explicitly join to another lang_id, or specific l.lang_id = 'en' somewhere.

If the issue is instead that a validation check is failing. It could be a problem with the SQLAlchemy mappings. You could let us know if anything looks off: https://github.com/gatheringhallstudios/MHWorldData/blob/master/mhdata/sql/mappings.py

**Comment by ardeaf** [comment]
Here's what I'm referencing:

**location_text schema:**
```
CREATE TABLE location_text (
	id INTEGER NOT NULL, 
	order_id INTEGER, 
	lang_id TEXT NOT NULL, 
	name TEXT, 
	**PRIMARY KEY (id, lang_id),** 
	FOREIGN KEY(lang_id) REFERENCES language (id)
)
```

Notice how the primary key is `(id, lang_id)`

Now pick a table that references this, for example **location item**:
```
CREATE TABLE location_item (
	id INTEGER NOT NULL, 
	location_id INTEGER, 
	area INTEGER, 
	rank TEXT, 
	item_id INTEGER, 
	stack INTEGER, 
	percentage INTEGER, 
	nodes INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	**FOREIGN KEY(location_id) REFERENCES location_text (id),** 
	FOREIGN KEY(item_id) REFERENCES item (id)
)
```

Foreign keys are supposed to reference primary or unique constrained keys. In this case, it only references the `id`, which is only part of the composite primary key in `location_text`.

I did some further research and it turns out that sqlite doesn't care about this by default (referential integrity) but instead opts to fail silently in the background:
https://cs.stanford.edu/people/widom/cs145/sqlite/SQLiteRefIntegrity.html

> Foreign key constraints are not checked by default. If you want SQLite to check any foreign key constraints specified on your tables, you must enable them with the command:
>
>`PRAGMA foreign_keys = ON;`
>once per database session (i.e. once per invocation of /usr/class/cs145/bin/sqlite). Even if you have previously enabled foreign key constraint checking while using a particular database, new sessions with that database will not check foreign key constraints unless you issue this PRAGMA command. If you do not issue this command, foreign key constraints are permitted to become violated, and it will happen in complete silence.



I'm unsure of the consequences of this either way, but it does prevent me from easily migrating the database to postgresql haha. I believe it is just a data integrity issue.

fwiw, I'm not a dba either.

If there are no negative impacts to keeping the sqlite database as is, then no need to fix, but just thought I'd point it out. I am fixing in my migration script by adding an intermediary table that has only an ID for each location:

```
CREATE TABLE location_id AS 
  SELECT DISTINCT id 
  FROM   location_text; 

ALTER TABLE location_id 
  ADD PRIMARY KEY (id); 
```

Then `location_item` and `location_text` would both reference this table instead.

**Comment by ardeaf** [comment]
Here's an [update from stackoverflow](https://stackoverflow.com/a/31797403) concerning how to set it up with sqlalchemy, although as I said before I'm unaware of any impacts (positive or negative) for this. Given that the data is automatically generated from game data, and users pretty much don't interact with the database, I don't see a huge benefit to enforcing referential integrity on the database -- but I could be wrong :).

**Comment by CarlosFdez** [comment]
If its silently ignored, that seems like a good enough reason for it to be fixed. I can tell you the reason isn't for referential integrity, it was because it seemed like the right practice (and because I wanted an index). I remember at one point I tried to setup a SQLAlchemy relationship and it didn't work, and this might actually be why.

That said, at the same time, since there's no negative effects in actually using the database in its current form, I'm probably going to keep it that way so long as I still have things I need to do (like Iceborne prep and fixing invalid data). I wouldn't be against someone fixing it though, but you did seem to find a workaround that worked great for your purposes.

The only things I can imagine is either making the location table itself in the source data (more future proof?) or replacing all location foreign keys with....something more suitable for that purpose. Like an index or something.

**Comment by ardeaf** [comment]
Actually, could it be that the foreign key should be moved from `location_item` to `location_text`?
```
CREATE TABLE location_text (
        ...
        PRIMARY KEY (id, lang_id), 
	...
)
```

```
CREATE TABLE location_item (
        ...
	FOREIGN KEY(location_id) REFERENCES location_text (id), 
        ...
)
```

Should it be like `weapon_text` which has a foreign key referencing a `weapon`?

```
CREATE TABLE weapon_text (
	id INTEGER NOT NULL, 
	lang_id TEXT NOT NULL, 
	name TEXT, 
	PRIMARY KEY (id, lang_id), 
	FOREIGN KEY(id) REFERENCES weapon (id), 
	FOREIGN KEY(lang_id) REFERENCES language (id)
)
```

```
CREATE TABLE weapon (
	id INTEGER NOT NULL, 
        ...
)
```

**Comment by ardeaf** [comment]
Pretty much finished with my migrations (using workaround above in postgres). I noticed that the `charm` table has a foreign key column `recipe_id` that seems to reference non-existent `recipe_id`. All rows reference a 4 digit number but there are no recipes that have 4 digits. Might be a placeholder or something? Or genuine mistake? See below:

![image](https://user-images.githubusercontent.com/20672831/70984289-48494f00-205e-11ea-98e9-008a3268886b.png)

**Comment by ardeaf** [comment]
One piece of invalid data I got during this foreign key thing was that Fair Wind Charm seems to be referencing a non existent recipe

Is there a guide on how to help get ready for iceborne? Once we get it, will we be able to get console user data as well?

**Comment by CarlosFdez** [comment]
Its because Fair Wind isn't craftable, its a pre-order bonus.

As to getting ready for iceborne, nah there's no guide. I've just been adding stuff as I can in an iceborne branch by hand. Sure once the formats are cracked for Iceborne I plan to use them to update data, but some data (like monsters) still have to be done by hand.

The actual limitation to adding console data ahead of time is lack of thorough information (no hitzones/droprate percents) and that I'm on PC only so I'd need to depend on volunteers to have it before its out on PC. The only reason detailed data of that sort exists for Iceborne is because of Japanese strategy guides, which don't have newer monsters.

**Comment by ardeaf** [comment]
Very nice. 

As for fair wind, wouldn't it make more sense to have it as `null` then? In my postgres migration i have to set it to null before setting the `recipe_id` foreign key on the `charm table`

I'll go ahead and close this issue to open up a new one regarding Iceborne help -- I have no idea where to start

**Comment by CarlosFdez** [comment]
I looked deeper into charm > recipe link. Its a bug. It was introduced when I changed how recipes to be a single table. I'll have it fixed in the iceborne branch.
